driver_config:
  digitalocean_access_token: <%= ENV['DIGITALOCEAN_API_TOKEN'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  instance_type: <%= ENV['EC2_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  retryable_tries: 120

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.0
    driver:
      name: ec2
      image_id: ami-c0b9a085
      instance_type: m3.medium
    transport:
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: ubuntu-12.04
    driver:
      name: ec2
      image_id: ami-c52476a0
      instance_type: m3.medium
    transport:
      username: ubuntu
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: ubuntu-14.04
    driver:
      name: ec2
      image_id: ami-3f02505a
      instance_type: m3.medium
    transport:
      username: ubuntu
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: centos-6
    driver:
      name: ec2
      image_id: ami-bc8131d4
      instance_type: m3.medium
    transport:
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: centos-7
    driver:
      name: ec2
      image_id: ami-61bbf104
      instance_type: m3.medium
    transport:
      username: centos
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: windows-2008r2
    driver:
      name: ec2
      image_id: ami-a7bbcac2
      instance_type: m3.medium
    transport:
      username: administrator
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: windows-2012r2
    driver:
      name: ec2
      image_id: ami-1df0ac78
      instance_type: m3.medium
    transport:
      username: administrator
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

suites:
 - name: default
   data_bags_path: test/integration/data_bags
   run_list:
     - recipe[data-bag-faker]
     - recipe[sumologic-collector::default]
   attributes:
     SUMO_ACCESS_ID: <%= ENV['SUMO_ACCESS_ID'] %>
     SUMO_ACCESS_KEY: <%= ENV['SUMO_ACCESS_KEY'] %>
